FROM ubuntu:24.04 AS builder

RUN apt-get update && apt-get install -y build-essential

WORKDIR /valkey
COPY Makefile .
COPY src/ src/
COPY deps/ deps/

RUN make -j$(nproc) BUILD_TLS=no

FROM ubuntu:24.04
RUN apt-get update && apt-get install -y libssl3t64 && rm -rf /var/lib/apt/lists/*
COPY --from=builder /valkey/src/valkey-server /usr/local/bin/
COPY --from=builder /valkey/src/valkey-cli /usr/local/bin/

EXPOSE 6379 16379
ENTRYPOINT ["valkey-server"]
