#!/usr/bin/env bash
set -euo pipefail

# Test script for Task 6: valkey-search Query Builder
# Usage: test.sh <workspace_dir>
# Validates that 6 FT.SEARCH/FT.AGGREGATE queries return correct results.

WORK_DIR="$(cd "${1:-.}" && pwd)"
PORT=6506
CONTAINER_NAME="bench-search-6"

PASS_COUNT=0
FAIL_COUNT=0

check() {
  local name="$1" result="$2"
  if [ "$result" = "0" ]; then
    echo "PASS: $name"
    PASS_COUNT=$((PASS_COUNT + 1))
  else
    echo "FAIL: $name"
    FAIL_COUNT=$((FAIL_COUNT + 1))
  fi
}

cleanup() {
  docker rm -f "$CONTAINER_NAME" 2>/dev/null || true
}
trap cleanup EXIT

# =========================================
# START VALKEY WITH SEARCH MODULE
# =========================================

echo "Starting valkey-bundle container on port $PORT..."
# Kill any container using our port or name
docker rm -f "$CONTAINER_NAME" 2>/dev/null || true
for cid in $(docker ps -q --filter "publish=$PORT" 2>/dev/null); do
  docker rm -f "$cid" 2>/dev/null || true
done
sleep 1
docker run -d --name "$CONTAINER_NAME" -p "$PORT:6379" valkey/valkey-bundle:latest >/dev/null 2>&1

# Wait for server to be ready
RETRIES=0
while ! docker exec "$CONTAINER_NAME" valkey-cli PING 2>/dev/null | grep -q "PONG"; do
  RETRIES=$((RETRIES + 1))
  if [ "$RETRIES" -gt 30 ]; then
    echo "FAIL: valkey-bundle container did not start within 30 seconds"
    echo ""
    echo "========================================="
    echo "Results: 0 passed, 1 failed out of 1 checks"
    echo "========================================="
    exit 1
  fi
  sleep 1
done
check "valkey-bundle container started" 0

# Verify search module is loaded
if docker exec "$CONTAINER_NAME" valkey-cli MODULE LIST 2>/dev/null | grep -qi "search"; then
  check "search module loaded" 0
else
  check "search module loaded" 1
  echo ""
  echo "========================================="
  echo "Results: $PASS_COUNT passed, $FAIL_COUNT failed out of $((PASS_COUNT + FAIL_COUNT)) checks"
  echo "========================================="
  exit 1
fi

# =========================================
# INSTALL DEPENDENCIES
# =========================================

echo ""
echo "Installing Python dependencies..."
pip install valkey -q 2>&1 || pip3 install valkey -q 2>&1 || true

# =========================================
# RUN SETUP
# =========================================

echo ""
echo "Running setup.py to load test data..."
cd "$WORK_DIR"
SETUP_OUTPUT=$(python3 setup.py 2>&1) && SETUP_EXIT=0 || SETUP_EXIT=$?

if [ "$SETUP_EXIT" = "0" ]; then
  check "setup.py completed successfully" 0
  echo "$SETUP_OUTPUT"
else
  echo "$SETUP_OUTPUT"
  check "setup.py completed successfully" 1
  echo ""
  echo "========================================="
  echo "Results: $PASS_COUNT passed, $FAIL_COUNT failed out of $((PASS_COUNT + FAIL_COUNT)) checks"
  echo "========================================="
  exit 1
fi

# Read expected counts from setup output
if [ ! -f "$WORK_DIR/expected_counts.json" ]; then
  echo "FAIL: expected_counts.json not generated by setup.py"
  exit 1
fi

EXPECTED_ELECTRONICS=$(python3 -c "import json; print(json.load(open('expected_counts.json'))['electronics'])")
EXPECTED_WIRELESS=$(python3 -c "import json; print(json.load(open('expected_counts.json'))['wireless'])")
EXPECTED_ELEC_INSTOCK_RATE4=$(python3 -c "import json; print(json.load(open('expected_counts.json'))['elec_instock_rate4'])")
EXPECTED_CATEGORIES=$(python3 -c "import json; print(len(json.load(open('expected_counts.json'))['categories']))")

echo ""
echo "Expected counts: electronics=$EXPECTED_ELECTRONICS wireless=$EXPECTED_WIRELESS elec_instock_rate4=$EXPECTED_ELEC_INSTOCK_RATE4 categories=$EXPECTED_CATEGORIES"

# =========================================
# STATIC CHECKS ON queries.py
# =========================================

echo ""
echo "Static analysis of queries.py..."

QF="$WORK_DIR/queries.py"

if [ ! -f "$QF" ]; then
  echo "FAIL: queries.py not found"
  echo ""
  echo "========================================="
  echo "Results: $PASS_COUNT passed, 1 failed out of $((PASS_COUNT + 1)) checks"
  echo "========================================="
  exit 1
fi

# Ensure queries.py does NOT contain FT.CREATE or FT.DROPINDEX
if grep -qE "FT\.CREATE|FT\.DROPINDEX|FT_CREATE|FT_DROPINDEX" "$QF" 2>/dev/null; then
  check "queries.py does NOT contain FT.CREATE/FT.DROPINDEX" 1
else
  check "queries.py does NOT contain FT.CREATE/FT.DROPINDEX" 0
fi

# Ensure NotImplementedError is NOT in the final version (all functions implemented)
NOT_IMPL_COUNT=$(grep -c "raise NotImplementedError" "$QF" 2>/dev/null || echo "0")
if [ "$NOT_IMPL_COUNT" = "0" ]; then
  check "all 6 functions implemented (no NotImplementedError)" 0
else
  check "all 6 functions implemented ($NOT_IMPL_COUNT still unimplemented)" 1
fi

# =========================================
# RUN QUERIES
# =========================================

echo ""
echo "Running queries.py..."
cd "$WORK_DIR"
QUERY_OUTPUT=$(python3 queries.py 2>&1) && QUERY_EXIT=0 || QUERY_EXIT=$?
echo "$QUERY_OUTPUT"

if [ "$QUERY_EXIT" = "0" ]; then
  check "queries.py executed without crash" 0
else
  check "queries.py executed without crash" 1
fi

# Check all 6 printed OK
OK_COUNT=$(echo "$QUERY_OUTPUT" | grep -c "^Q[1-6]: OK" || echo "0")
if [ "$OK_COUNT" = "6" ]; then
  check "all 6 queries returned OK" 0
else
  check "all 6 queries returned OK ($OK_COUNT/6)" 1
fi

# =========================================
# VALIDATE results.json
# =========================================

echo ""
echo "Validating results.json..."

if [ ! -f "$WORK_DIR/results.json" ]; then
  check "results.json exists" 1
  echo ""
  echo "========================================="
  echo "Results: $PASS_COUNT passed, $FAIL_COUNT failed out of $((PASS_COUNT + FAIL_COUNT)) checks"
  echo "========================================="
  exit 1
fi
check "results.json exists" 0

# Write validation script to a temp file to avoid bash quoting issues
VALIDATE_SCRIPT=$(mktemp /tmp/validate_XXXXXX.py)
cat > "$VALIDATE_SCRIPT" <<'PYEOF'
import json, sys

with open('results.json') as f:
    results = json.load(f)

with open('expected_counts.json') as f:
    expected = json.load(f)

errors = []
passes = []

# --- Q1: fulltext 'wireless' - non-empty list ---
q1 = results.get('q1')
if q1 is None:
    errors.append('Q1: result is None')
elif not isinstance(q1, list):
    errors.append(f'Q1: expected list, got {type(q1).__name__}')
elif len(q1) == 0:
    errors.append('Q1: result is empty list')
elif len(q1) != expected['wireless']:
    errors.append(f"Q1: expected {expected['wireless']} matches, got {len(q1)}")
else:
    passes.append(f"Q1: found {len(q1)} wireless products (correct)")

# --- Q2: numeric range 100-500, sorted ascending ---
q2 = results.get('q2')
if q2 is None:
    errors.append('Q2: result is None')
elif not isinstance(q2, list):
    errors.append(f'Q2: expected list, got {type(q2).__name__}')
elif len(q2) == 0:
    errors.append('Q2: result is empty list')
else:
    prices_valid = True
    sorted_asc = True
    prev_price = -1
    for item in q2:
        if not isinstance(item, (list, tuple)) or len(item) != 2:
            errors.append(f'Q2: item is not a 2-element tuple/list: {item}')
            prices_valid = False
            break
        try:
            p = float(item[1])
        except (ValueError, TypeError):
            errors.append(f'Q2: price is not a number: {item[1]}')
            prices_valid = False
            break
        if p < 100 or p > 500:
            errors.append(f'Q2: price {p} out of range [100, 500]')
            prices_valid = False
            break
        if p < prev_price:
            sorted_asc = False
        prev_price = p
    if prices_valid:
        passes.append(f'Q2: all {len(q2)} prices in range [100, 500]')
    if sorted_asc and prices_valid:
        passes.append('Q2: prices sorted ascending')
    elif prices_valid:
        errors.append('Q2: prices NOT sorted ascending')

# --- Q3: tag filter Electronics - exact count ---
q3 = results.get('q3')
if q3 is None:
    errors.append('Q3: result is None')
elif not isinstance(q3, int):
    errors.append(f'Q3: expected int, got {type(q3).__name__}')
elif q3 != expected['electronics']:
    errors.append(f"Q3: expected {expected['electronics']} Electronics, got {q3}")
else:
    passes.append(f'Q3: Electronics count = {q3} (correct)')

# --- Q4: combined filter - non-empty, all Electronics+rating>=4+instock ---
q4 = results.get('q4')
if q4 is None:
    errors.append('Q4: result is None')
elif not isinstance(q4, list):
    errors.append(f'Q4: expected list, got {type(q4).__name__}')
elif len(q4) == 0:
    errors.append('Q4: result is empty list')
elif len(q4) != expected['elec_instock_rate4']:
    errors.append(f"Q4: expected {expected['elec_instock_rate4']} items, got {len(q4)}")
else:
    passes.append(f'Q4: combined filter returned {len(q4)} items (correct)')

# --- Q5: aggregate avg price per category ---
q5 = results.get('q5')
if q5 is None:
    errors.append('Q5: result is None')
elif not isinstance(q5, dict):
    errors.append(f'Q5: expected dict, got {type(q5).__name__}')
elif len(q5) != len(expected.get('categories', [])):
    errors.append(f"Q5: expected {len(expected.get('categories', []))} categories, got {len(q5)}")
else:
    all_positive = all(
        isinstance(v, (int, float)) and v > 0
        for v in q5.values()
    )
    if all_positive:
        passes.append(f'Q5: {len(q5)} categories with positive avg prices')
    else:
        errors.append('Q5: some avg prices are not positive numbers')

# --- Q6: pagination - exactly 10 items ---
q6 = results.get('q6')
if q6 is None:
    errors.append('Q6: result is None')
elif not isinstance(q6, list):
    errors.append(f'Q6: expected list, got {type(q6).__name__}')
elif len(q6) != 10:
    errors.append(f'Q6: expected 10 items (page 3), got {len(q6)}')
else:
    passes.append('Q6: page 3 returned exactly 10 items')

# Print results
for p in passes:
    print(f'PASS_DETAIL: {p}')
for e in errors:
    print(f'FAIL_DETAIL: {e}')
print(f'SUMMARY: {len(passes)} passed, {len(errors)} failed')
sys.exit(1 if errors else 0)
PYEOF

VALIDATE_OUTPUT=$(python3 "$VALIDATE_SCRIPT" 2>&1) && VALIDATE_EXIT=0 || VALIDATE_EXIT=$?
rm -f "$VALIDATE_SCRIPT"

echo "$VALIDATE_OUTPUT"

# Parse validation results
Q1_OK=1; Q2_OK=1; Q3_OK=1; Q4_OK=1; Q5_OK=1; Q6_OK=1

if echo "$VALIDATE_OUTPUT" | grep -q "PASS_DETAIL: Q1:"; then Q1_OK=0; fi
if echo "$VALIDATE_OUTPUT" | grep -q "PASS_DETAIL: Q2: all"; then Q2_OK=0; fi
if echo "$VALIDATE_OUTPUT" | grep -q "PASS_DETAIL: Q3:"; then Q3_OK=0; fi
if echo "$VALIDATE_OUTPUT" | grep -q "PASS_DETAIL: Q4:"; then Q4_OK=0; fi
if echo "$VALIDATE_OUTPUT" | grep -q "PASS_DETAIL: Q5:"; then Q5_OK=0; fi
if echo "$VALIDATE_OUTPUT" | grep -q "PASS_DETAIL: Q6:"; then Q6_OK=0; fi

check "Q1: fulltext search for 'wireless'" "$Q1_OK"
check "Q2: numeric range 100-500, sorted ascending" "$Q2_OK"
check "Q3: tag filter Electronics count" "$Q3_OK"
check "Q4: combined filter (Electronics + rating>=4 + in_stock)" "$Q4_OK"
check "Q5: aggregate avg price per category" "$Q5_OK"
check "Q6: pagination (page 3, 10 items)" "$Q6_OK"

# Check Q2 sort order separately
Q2_SORT=1
if echo "$VALIDATE_OUTPUT" | grep -q "PASS_DETAIL: Q2: prices sorted"; then Q2_SORT=0; fi
check "Q2: sort order verified ascending" "$Q2_SORT"

# =========================================
# SUMMARY
# =========================================

echo ""
echo "========================================="
echo "Results: $PASS_COUNT passed, $FAIL_COUNT failed out of $((PASS_COUNT + FAIL_COUNT)) checks"
echo "========================================="

if [ "$FAIL_COUNT" -gt 0 ]; then
  exit 1
fi
