services:
  valkey:
    image: valkey/valkey:8.1
    ports:
      - "6409:6379"
    command: >
      valkey-server
      --loadmodule /usr/lib/valkey/modules/json.so
    healthcheck:
      test: ["CMD", "valkey-cli", "ping"]
      interval: 2s
      timeout: 3s
      retries: 10
